<?php

namespace W3com\BoomBundle\HanaEnum;

class ApprovalTemplatesDocumentTypeEnum
{
	const ATDTQUOTATION = '';
	const ATDTORDER = '';
	const ATDTDELIVERY = '';
	const ATDTRETURNS = '';
	const ATDTARDOWNPAYMENT = '';
	const ATDTARINVOICE = '';
	const ATDTARCREDITMEMO = '';
	const ATDTCORRECTIONINVOICE = '';
	const ATDTPURCHASEORDER = '';
	const ATDTGOODSRECEIPTPO = '';
	const ATDTGOODSRETURNS = '';
	const ATDTAPDOWNPAYMENT = '';
	const ATDTAPINVOICE = '';
	const ATDTAPCREDITMEMO = '';
	const ATDTGOODSRECEIPT = '';
	const ATDTGOODSISSUE = '';
	const ATDTINVENTORYTRANSFER = '';
	const ATDTPURCHASEQUOTATION = '';
	const ATDTINVENTORYTRANSFERREQUEST = '';
	const ATDTOUTGOINGPAYMENT = '';
	const ATDTINVENTORYCOUNTING = '';
	const ATDTINVENTORYPOSTING = '';
	const ATDTINVENTORYOPENINGBALANCE = '';
}
