<?php

namespace W3com\BoomBundle\HanaEnum;

class BoChangeLogEnum
{
	const CLCHARTOFACCOUNTS = '';
	const CLBUSINESSPARTNERS = '';
	const CLITEMS = '';
	const CLVATGROUPS = '';
	const CLUSERS = '';
	const CLINVOICES = '';
	const CLCREDITNOTES = '';
	const CLDELIVERYNOTES = '';
	const CLRETURNS = '';
	const CLORDERS = '';
	const CLPURCHASEINVOICES = '';
	const CLPURCHASECREDITNOTES = '';
	const CLPURCHASEDELIVERYNOTES = '';
	const CLPURCHASERETURNS = '';
	const CLPURCHASEORDERS = '';
	const CLQUOTATIONS = '';
	const CLINCOMINGPAYMENTS = '';
	const CLJOURNALENTRIES = '';
	const CLCREDITCARDS = '';
	const CLADMININFO = '';
	const CLVENDORPAYMENTS = '';
	const CLITEMGROUPS = '';
	const CLINVENTORYGENERALENTRY = '';
	const CLINVENTORYGENERALEXIT = '';
	const CLWAREHOUSES = '';
	const CLPRODUCTTREES = '';
	const CLSTOCKTRANSFERS = '';
	const CLFINANCEPERIODS = '';
	const CLADDITIONALEXPENSES = '';
	const CLPICKLISTS = '';
	const CLMATERIALREVALUATION = '';
	const CLCORRECTIONPURCHASEINVOICE = '';
	const CLCORRECTIONPURCHASEINVOICEREVERSAL = '';
	const CLCORRECTIONINVOICE = '';
	const CLCORRECTIONINVOICEREVERSAL = '';
	const CLEMPLOYEESINFO = '';
	const CLCUSTOMEREQUIPMENTCARDS = '';
	const CLWITHHOLDINGTAXCODES = '';
	const CLBILLOFEXCHANGE = '';
	const CLSERVICECALLS = '';
	const CLPRODUCTIONORDERS = '';
	const CLDOWNPAYMENTS = '';
	const CLPURCHASEDOWNPAYMENTS = '';
	const CLPERIODCATEGORY = '';
	const CLHOUSEBANKACCOUNTS = '';
	const CLSALESTAXINVOICE = '';
	const CLPURCHASETAXINVOICE = '';
	const CLEXTERNALBANKOPERATIONCODES = '';
	const CLINTERNALBANKOPERATIONCODES = '';
	const CLOUTGOINGEXCISEINVOICE = '';
	const CLINCOMINGEXCISEINVOICE = '';
	const CLINVENTORYTRANSFERREQUESTS = '';
	const CLPURCHASEQUOTATION = '';
	const CLUDO = '';
}
