<?php

namespace W3com\BoomBundle\HanaEnum;

class BoDeductionTaxGroupCodeEnum
{
	const DTGCINTERESTRECEIVERS = '';
	const DTGCEMPLOYEERECEIVINGCOMMISSION = '';
	const DTGCWRITERSPRICE = '';
	const DTGCPAIDSERVICES = '';
	const DTGCPAYMENTSTOFOREIGNCITIZENS = '';
	const DTGCPAYMENTSFORCITIZENSINFOREIGNCOUNTRIES = '';
	const DTGCINVALIDPAYMENTFROMCOMPENSATIONFUND = '';
	const DTGCREPAYMENTTOEMPLOYERFROMCOMPENSATIONFUND = '';
	const DTGCRENTALPAYMENTS = '';
	const DTGCPAYMENTSFROMSTUDYFUND = '';
	const DTGCDIVIDENDPAYMENTS = '';
}
