<?php

namespace W3com\BoomBundle\HanaEnum;

class BrazilNumericIndexerTypes
{
	const BNITINVALID = '';
	const BNITBEVERAGECOMMERCIALBRAND = '';
	const BNITFUELGROUP = '';
	const BNITNATUREOFCOMPANY = '';
	const BNITECONOMICACTIVITYTYPE = '';
	const BNITCOOPERATIVEASSOCIATIONTYPE = '';
	const BNITPROFITTAXATION = '';
	const BNITCOMPANYQUALIFICATION = '';
	const BNITDECLARERTYPE = '';
	const BNITENVIRONMENTTYPE = '';
	const BNITTRIBUTARYTYPE = '';
	const BNITTRIBUTARYREGIMECODE = '';
	const BNITINCOMENATURETABLE = '';
	const BNITINCOMENATURECODE = '';
	const BNITEXPORTATIONDOCUMENTTYPE = '';
	const BNITEXPORTATIONNATURE = '';
	const BNITLADINGBILLTYPE = '';
}
