<?php

namespace W3com\BoomBundle\HanaEnum;

class DocumentPriceSourceEnum
{
    const DPSSPECIALPRICESFORBUSINESSPARTNER = '';
    const DPSMANUAL = '';
    const DPSACTIVEPRICELISTDISCOUNTGROUPS = '';
    const DPSACTIVEPRICELIST = '';
    const DPSINACTIVEPRICELIST = '';
    const DPSBLANKETAGREEMENT = '';
    const DPSPERIODANDVOLUMEDISCOUNTS = '';
    const DPSPERIODANDVOLUMEDISCOUNTSDISCOUNTGROUPS = '';
    const DPSINACTIVEPRICELISTDISCOUNTGROUPS = '';
    const DPSNEWSPECIALPRICESFORBUSINESSPARTNER = '';
    const DPSNEWACTIVEPRICELISTDISCOUNTGROUPS = '';
    const DPSNEWACTIVEPRICELIST = '';
    const DPSNEWINACTIVEPRICELIST = '';
    const DPSNEWBLANKETAGREEMENT = '';
    const DPSNEWPERIODANDVOLUMEDISCOUNTS = '';
    const DPSNEWPERIODANDVOLUMEDISCOUNTSDISCOUNTGROUPS = '';
    const DPSNEWINACTIVEPRICELISTDISCOUNTGROUPS = '';
}
