<?php

namespace W3com\BoomBundle\HanaEnum;

class InventoryPostingCopyOptionEnum
{
	const IPCONOCOUNTERSDIFF = '';
	const IPCOINDIVIDUAL1COUNTEDQUANTITY = '';
	const IPCOINDIVIDUAL2COUNTEDQUANTITY = '';
	const IPCOINDIVIDUAL3COUNTEDQUANTITY = '';
	const IPCOINDIVIDUAL4COUNTEDQUANTITY = '';
	const IPCOINDIVIDUAL5COUNTEDQUANTITY = '';
	const IPCOTEAMCOUNTEDQUANTITY = '';
}
