<?php

namespace W3com\BoomBundle\HanaEnum;

class InventoryAccountTypeEnum
{
	const IATEXPENSES = '';
	const IATREVENUES = '';
	const IATEXEMPTINCOME = '';
	const IATINVENTORY = '';
	const IATCOST = '';
	const IATTRANSFER = '';
	const IATVARIENCE = '';
	const IATPRICEDIFFERENCE = '';
	const IATNEGATIVEINVENTORYADJUSTMENT = '';
	const IATDECREASING = '';
	const IATINCREASING = '';
	const IATRETURNING = '';
	const IATEUREVENUES = '';
	const IATEUEXPENSES = '';
	const IATFOREIGNREVENUE = '';
	const IATFOREIGNEXPENS = '';
	const IATPURCHASE = '';
	const IATPARETURN = '';
	const IATPURCHASEOFFSET = '';
	const IATEXCHANGERATEDIFFERENCES = '';
	const IATGOODSCLEARING = '';
	const IATGLDECREASE = '';
	const IATGLINCREASE = '';
	const IATWIP = '';
	const IATWIPVARIANCE = '';
	const IATWIPOFFSETPROFITANDLOSS = '';
	const IATINVENTORYOFFSETPROFITANDLOSS = '';
	const IATSTOCKINFLATIONADJUST = '';
	const IATSTOCKINFLATIONOFFSET = '';
	const IATCOSTINFLATION = '';
	const IATCOSTINFLATIONOFFSET = '';
	const IATEXPENSECLEARING = '';
	const IATEXPENSEOFFSETTING = '';
	const IATSTOCKINTRANSIT = '';
	const IATSHIPPEDGOODS = '';
	const IATVATINREVENUE = '';
	const IATSALESCREDIT = '';
	const IATPURCHASECREDIT = '';
	const IATEXEMPTEDCREDITS = '';
	const IATSALESCREDITFOREIGN = '';
	const IATFOREIGNPURCHASECREDIT = '';
	const IATSALESCREDITEU = '';
	const IATEUPURCHASECREDIT = '';
	const IATPURCHASEBALANCE = '';
	const IATWHINCOMINGCENVAT = '';
	const IATWHOUTGOINGCENVAT = '';
	const IATFREEOFCHARGESALES = '';
	const IATFREEOFCHARGEPURCHASE = '';
}
