<?php

namespace W3com\BoomBundle\HanaEnum;

class OperationCodeTypeEnum
{
	const OCTSUMMARYINVOICESENTRY = '';
	const OCTSUMMARYRECEIPTSENTRY = '';
	const OCTINVOICEWITHSEVERALVATRATES = '';
	const OCTCORRECTIONINVOICE = '';
	const OCTDUEVATPENDINGINVOICEISSUANCE = '';
	const OCTEXPENSESINCURREDBYTRAVELAGENTFORCUSTOMERS = '';
	const OCTSPECIALREGULATIONFORVATGROUP = '';
	const OCTSPECIALREGULATIONFORGOLDINVESTMENT = '';
	const OCTREVERSECHARGEPROCEDURE = '';
	const OCTUNSUMMARIZEDRECEIPTS = '';
	const OCTIDENTIFICATIONOFERRORTRANSACTIONS = '';
	const OCTTRANSACTIONSWITHENTREPRENEURSISSUINGRECEIPTSFORAGRICULTURALCOMPENSATION = '';
	const OCTSERVICEINVOICINGBYTRAVELAGENCIESONBEHALFOFTHIRDPARTIES = '';
	const OCTBUSINESSOFFICERENTAL = '';
	const OCTSUBSIDIES = '';
	const OCTINCOMINGPAYMENTSFORINDUSTRIALANDINTELLECTUALPROPERTYRIGHTS = '';
	const OCTINSURANCETRANSACTIONS = '';
	const OCTPURCHASESFROMTRAVELAGENCIES = '';
	const OCTTRANSACTIONSSUBJECTTOPRODUCTIONSERVICEANDIMPORTTAXESINCEUTAANDMELILLA = '';
}
