<?php

namespace W3com\BoomBundle\HanaEnum;

class ResourceCapacityActionEnum
{
	const RCAUNKNOWN = '';
	const RCAPRODUCTIONORDERCREATE = '';
	const RCAPRODUCTIONORDERCLOSE = '';
	const RCAPRODUCTIONORDERRESCHEDULE = '';
	const RCAPRODUCTIONORDERADDLINE = '';
	const RCAPRODUCTIONORDERDELETELINE = '';
	const RCAPRODUCTIONORDERUPDATELINE = '';
	const RCAISSUEFORPRODUCTIONCREATE = '';
	const RCARECEIPTFROMPRODUCTIONCREATE = '';
}
