<?php

namespace W3com\BoomBundle\HanaEnum;

class SPEDContabilQualificationCodeEnum
{
	const SPEDNA = '';
	const SPEDDIRETOR = '';
	const SPEDCONSELHEIRODEADMINISTRACAO = '';
	const SPEDADMINISTRADOR = '';
	const SPEDADMINISTRADORDOGRUPO = '';
	const SPEDADMINISTRADORDESOCIEDADEFILIADA = '';
	const SPEDADMINISTRADORJUDICIALPESSOAFISICA = '';
	const SPEDADMINISTRADORJUDICIALPESSOAJURIDICAPROFISSIONALRESPONSAVEL = '';
	const SPEDADMINISTRADORJUDICIALGESTOR = '';
	const SPEDGESTORJUDICIAL = '';
	const SPEDPROCURADOR = '';
	const SPEDINVENTARIANTE = '';
	const SPEDLIQUIDANTE = '';
	const SPEDINTERVENTOR = '';
	const SPEDEMPRESARIO = '';
	const SPEDCONTADOR = '';
	const SPEDOUTROS = '';
}
