<?php

namespace W3com\BoomBundle\HanaEnum;

class StraightLineCalculationMethodEnum
{
	const SLCMAUQUISITIONVALUEDIVIDEDBYTOTALUSEFULLIFE = '';
	const SLCMPERCENTAGEOFACQUISITIONVALUE = '';
	const SLCMNETBOOKVALUEDIVIDEDBYREMAININGLIFE = '';
}
