<?php

namespace W3com\BoomBundle\HanaEnum;

class TransTypesEnum
{
	const TTALLTRANSACTIONS = '';
	const TTOPENINGBALANCE = '';
	const TTCLOSINGBALANCE = '';
	const TTARINVOICE = '';
	const TTARCREDITNOTE = '';
	const TTDELIVERY = '';
	const TTRETURN = '';
	const TTAPINVOICE = '';
	const TTAPCREDITNOTE = '';
	const TTPURCHASEDELIVERYNOTE = '';
	const TTPURCHASERETURN = '';
	const TTRECEIPT = '';
	const TTDEPOSIT = '';
	const TTJOURNALENTRY = '';
	const TTVENDORPAYMENT = '';
	const TTCHEQUESFORPAYMENT = '';
	const TTSTOCKLIST = '';
	const TTGENERALRECEIPTTOSTOCK = '';
	const TTGENERALRELEASEFROMSTOCK = '';
	const TTTRANSFERBETWEENWAREHOUSES = '';
	const TTWORKINSTRUCTIONS = '';
	const TTLANDEDCOSTS = '';
	const TTDEFERREDDEPOSIT = '';
	const TTCORRECTIONINVOICE = '';
	const TTINVENTORYVALUATION = '';
	const TTAPCORRECTIONINVOICE = '';
	const TTAPCORRECTIONINVOICEREVERSAL = '';
	const TTARCORRECTIONINVOICE = '';
	const TTARCORRECTIONINVOICEREVERSAL = '';
	const TTBOETRANSACTION = '';
	const TTPRODUCTIONORDER = '';
	const TTDOWNPAYMENT = '';
	const TTPURCHASEDOWNPAYMENT = '';
	const TTINTERNALRECONCILIATION = '';
}
