services:
  W3com\BoomBundle\Service\BoomManager:
    arguments:
      - '%boom.config%'
      - '@logger'
      - '@debug.stopwatch'
      - '@Symfony\Component\Cache\Adapter\AdapterInterface'
    tags:
      - { name: monolog.logger.generator, channel: hana }
    public: true

  W3com\BoomBundle\Service\HanaConfigManager:
    arguments:
      - '@W3com\BoomBundle\Service\BoomManager'
      - '@Symfony\Component\Cache\Adapter\AdapterInterface'
    public: true

  W3com\BoomBundle\DataCollector\HanaDataCollector:
    arguments:
      - '@W3com\BoomBundle\Service\BoomManager'
    tags:
      - { name: data_collector, template: '@W3comBoom/profiler/toolbar.html.twig', id: 'boom.hana_collector'}
    public: true

  W3com\BoomBundle\Service\BoomGenerator:
    arguments:
      - '@W3com\BoomBundle\Service\BoomManager'
      - '@Symfony\Component\Cache\Adapter\AdapterInterface'
    public: true

  W3com\BoomBundle\Command\UpdateViewsCommand:
    arguments:
      - '@W3com\BoomBundle\Service\BoomManager'
    tags:
      - { name: 'console.command', command: 'boom:update-views' }

  W3com\BoomBundle\Command\UpdateViewCommand:
    arguments:
      - '@W3com\BoomBundle\Service\BoomManager'
    tags:
      - { name: 'console.command', command: 'boom:update-view' }

